### ISSUE TITLE
"ForbiddenError: invalid csrf token", but only sometimes.

### ISSUE THREAD

**Issue by Monokai** [expressjs/csurf#204]
I'm running an app via Docker on 3 servers. The servers are load balanced. I'm using Node 12 and Express. This is the relevant setup code:

```js
import session from 'express-session';

//…

const MongoStore = connectMongo(session);

const sessionStore = new MongoStore({
	mongooseConnection: database.connection, // mongoose.connection
	collection        : 'sessions',
	stringify         : false
});

app.use(session({
	domain           : 'domain.com',
	name             : 'mycookie',
	secret           : 'mysecret',
	resave           : false,
	saveUninitialized: false,
	store            : sessionStore,
	cookie           : {
		secure           : APP.PRODUCTION,
		httpOnly         : true,
		resave           : false,
		saveUninitialized: false,
		maxAge           : 7776000 * 1000
	}
}));
```

I have a couple of post requests that need a csrfToken. I had placed the token in the head tag of html before, but that prevented caching. So now I'm first requesting a csrf token before I post a request using that token. I'm using this on the server:

```js
app.use(csrf());

app.get('/get-token', (req, res) => res.json({
	csrfToken: req.csrfToken()
});
```

And this on the client:

```js
const csrfResult = await fetch('/get-token', {
	cache: 'no-store' // just in case
});

const csrfJSON = await csrfResult.json();

const result = await fetch('/request', {
	credentials: 'same-origin',
	method     : 'POST',
	redirect   : 'error',
	headers    : new Headers({
		'Accept'      : 'application/json',
		'Content-Type': 'application/json; charset=utf-8',
		'CSRF-Token'  : csrfJSON.csrfToken
	}),
	body: JSON.stringify({
		//…
	})
});

json = await result.json().catch(e => {
	console.error(`error: ${e.message}`);
});
```

Nginx removes all cache headers for location `/get-token`:
```nginx
add_header Last-Modified $date_gmt;
add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
if_modified_since off;
expires off;
etag off;

#…
```

And this works fine.

But every now and then, I'm getting `ForbiddenError: invalid csrf token` lines in my server logs. And it happens too often to be just a fluke. I'm working on this issue for a while now and I cannot figure out where things go wrong.

Do I miss something?

**Comment by Monokai** [comment]
Hmm, I'm caching the responses in parts of my app and I think this has something to do with it. I'm using express middleware like this:

```js
function (req, res, next) {

	//…

	const cached = memoryCache.get(key); // key depends on req.originalURL and flash message content

	if (cached) {
		res.send(cached);
	} else {
		const sendResponse = res.send;

		res.send = body => {
			memoryCache.put(key, body, duration * 1000);
			sendResponse.call(res, body);
		};

		next();
	}
}```

I'm caching the body of the response (e.g. the entire homepage), but I don't understand why this should impact the invalid CSRF tokens. Any ideas?

**Comment by Monokai** [comment]
I've also tried setting the load balancer to use sticky sessions, so that the requests from one user stay at the same machine, but still no dice, I keep getting invalid csrf token errors in my log. I cannot get my app to emit errors on my local machine via multiple browser tabs, so it's hard to debug. Does anybody have any pointers for what kind of things I should be looking for to fix this? @dougwilson any ideas?

**Comment by dougwilson** [comment]
> Does anybody have any pointers for what kind of things I should be looking for to fix this? @dougwilson any ideas?

Not off-hand. If you can provide a way to reproduce the issue I am happy to debug though it to determine what is wrong.

**Comment by Monokai** [comment]
I cannot get it to reproduce. I only *sometimes* (~1% of visitors) see it in the live environment. If I test the live environment with Postman, it looks OK from my site.

Maybe these visitors have cookies disabled? Then the session ID cannot be retrieved and CSRF doesn't work right? Or there's something else going on, delays or race conditions in saving session data to the store or something. Still no solution yet.

**Comment by dougwilson** [comment]
Well, a live environment is also going to have users / clients also trying to do the very thing that csrf is designed to block, so there will always be some amount of those showing up if it's a live environment.

**Comment by Monokai** [comment]
I understand your point, but I really think that's not the case here. I see too many requests in my logs that are erroneous in relation to other normal requests. For example, this is a random erroneous request that I'm seeing (I'm using sentry.io for my logs):

**json body**
```js
{
	"_csrf": "9OWbdCyM-FqyYkq-k-nAWJLd35jV5QSjxTwo",
	"name": "my-name"
}
```

**cookie:** (I'm using an uuid for the cookie name)
```
10c38004-cbdc-4f85-8106-54e2a60682a8	s:UiybGvPrPUfIEO9d3AAobn0XRE-aLPnk.2yGzNby8Vz5DpuKkaNpLlACkCY21XtZSSyN3fg/DQb8
```

**headers**
```
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	gzip, deflate, br
Accept-Language	nl-NL
Cache-Control	max-age=0
Connection	upgrade
Content-Length	253
Content-Type	application/x-www-form-urlencoded
Host	mydomain.com
Referer	mydomain.com/url
Upgrade-Insecure-Requests	1
User-Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
X-Forwarded-For	194.171.51.6, 10.0.0.3
X-Forwarded-Port	443
X-Forwarded-Proto	https
X-Nginx-Proxy	true
X-Real-Ip	10.0.0.3
```

Do you see anything strange here? I'm at a loss.

**Comment by dougwilson** [comment]
Thanks @Monokai that does help. The contents of the cookie is the secret used to compare against the incoming CSRF token. In your example above, the the incoming token is `9OWbdCyM-FqyYkq-k-nAWJLd35jV5QSjxTwo`. The way that validation works it that the token is split at the first `-` to get the salt + value, `9OWbdCyM` and `FqyYkq-k-nAWJLd35jV5QSjxTwo` in this case, with the expectation that the salt + the secret = the value.

Since the secret is stored within your session in your example, I cannot see what it is, but presumably it does not match. If that is the case, it would ultimately mean that the token and secret are out-of-sync in your app somehow. That would be if a new session was created maybe and then the old token was still on the client side, perhaps.

**Comment by Monokai** [comment]
@dougwilson Thanks. I've logged the session IDs and I can see the session ID of the incoming request matches the one that's stored in the cookie. I've also logged the `csrfSecret` of those sessions. These are three requests that throw `ForbiddenError`:

```
csrfSecret: DpKaWmYiVh79EskQyGqnhJKW
_csrf token: Jt645PGA-s2KRFOHGAiyi4Pj438CWSJrEzY8

csrfSecret: _nmUGqvfdim6OhIM8SPTsduj
_csrf token: wJhEKsqQ-VEe29vBXH9XBmc4wepib_vvVnNc

csrfSecret: BpkGrTELH4eWJgk6bhXBbaNU
_csrf token: R5feoGAT-FZwMIgFvykt25unz3DYHhHeMtnI
```

Can you see anything that goes wrong here?

You mention that the token and secret could be out-of-sync. That sounds logical, but what could be the scenarios in which this could happen? Maybe `express-session` is too slow with saving the csrf tokens?

I'm trying to solve this for weeks now but it's so hard to test, because I can't trigger it myself locally or remotely.

Any pointers are welcome.

**Comment by Monokai** [comment]
@dougwilson any ideas? It's unfortunately beginning to impact too many users. I also see new Github issues coming up that look like they have the same problem.

It looks like the combination of `csurf`, `express-session` and `connect-mongo` somehow cause the sessions to be out of sync. Do you have any experience with problems caused by this combination?

**Comment by dougwilson** [comment]
I am not sure, off-hand. Is it possible to provide instructions where I can set up an environment that has these issue to try and work through with a debugger attached? It may provide insight into what the issue it. I definitely would like whatever it is fixed, don't get me wrong :) just don't know what is wrong.

**Comment by Monokai** [comment]
I understand you're trying to help, no worries :) And I know how hard it is to provide support, so thanks so far.

I cannot provide you a complete copy of the codebase I'm having issues with. That would cause too many legal issues unfortunately. I realize that's also what makes it hard to say anything about this. I tried to extract the core code in the first issues. But it all just seems very regular.

The only thing that's different in the live environment so far as I can see, is that I have a docker environment running 3 different servers with a load balancer in front of it. And I use a remote database with MongoStore. But that should just work right?

What I can do is attach your debugger for a while and use remote logging to report back?

**Comment by js-kyle** [comment]
@Monokai I too am having this exact issue, with the combination of `csurf`, `express-session` and `connect-mongo` and I am also passing a Mongoose connection to `connect-mongo`. I'm in the same situation of debugging this so I'll ensure to update this issue with anything I find.

**Comment by js-kyle** [comment]
At this stage I think it's just an intermittent error coming from the session store. I'm going to look into trying to prove this theory

**Comment by Monokai** [comment]
It's almost inevitable right? I've looked through the `csurf` code, and although it's hard to say, I can't find anything that looks like it might cause this bug. Coupled with the fact that I only see it in live environments, I think it must be a delay or race-condition in saving the session data. Either caused by `express-session` or `connect-mongo`.

For this reason I also use `session.save()` statements in my code, to be sure the sessions are saved, but I still haven't found a solution.

**Comment by nirmalbenny** [comment]
I'm stuck with the same issue and i noticed that the csrf token value stored in the session store is not getting updated with new token values generated . This could be causing the token mismatch?

**Comment by js-kyle** [comment]
@nirmalbenny are you also using the combination of ` csurf`, `express-session` and `connect-mongo`? Or just `csurf`?

**Comment by js-kyle** [comment]
but yes this sounds very related, do you have any way to reliably reproduce?

**Comment by kwameopareasiedu** [comment]
Same issue here. For me, it seems this happens on an environment with multiple servers managed by a balancer...
My theory is during the page GET request, server A sets up the cookie, but on form POST, another server handles the request and does not recognize the content setup in the cookie from server A...

**Comment by kwameopareasiedu** [comment]
It has never happened in a development or staging environment since it's only one server there...

**Comment by kwameopareasiedu** [comment]
I decided to use an external Redis store (AWS) for the session store... but funny enough... a chunk of users still experience this issue...

**Comment by kwameopareasiedu** [comment]
I finally got rid of the error. Apparently it was a server configuration issue causing the cookie not to be set on the client's browser, hence no token was submitted.

The steps I took were the following:

- Add `app.set("trust proxy", 1);` to your express configuration...
- For any AJAX POST request to the server, set `withCredentials` to true for the browser to submit all cookies...

Hope this helps...

**Comment by Monokai** [comment]
Hey @kwameopareasiedu thanks for your update. I'm already doing both. I'm using fetch though, with `credentials: 'same-origin'`.

**Comment by Monokai** [comment]
@js-kyle have you found anything yet? I'm still having the same problems. Very curious if you solved this.

**Comment by js-kyle** [comment]
Hey @Monokai. I feel like everyone in this thread might be having different issues. There are quite a few elements at play, both code and config errors which could lead to this. I fixed it in my application but I'm not sure my fix would help you.

In my case I was able to 'fix it' by forking `connect-mongo` privately and modifying the `$or` filter on this line https://github.com/jdesboeufs/connect-mongo/blob/master/src/index.js#L231. As my application uses the Azure CosmosDB Mongo API, that something was not right with the use of $or (CosmosDB only supports a basic Mongo feature set). I removed the $exists: true filter

We still see a few random errors but I believe these to be genuine errors - like forms open on the page for longer than the session expiry date. I really dont see why it fixes the error - there is something more happening here

**Comment by Monokai** [comment]
@js-kyle thanks for letting me know. That's a quite an obscure bug :)

Allright, I guess I have to dig deeper then!

**Comment by sureshdeepalh** [comment]
I'm also facing the same issue here. My login form it is working fine. But same application one another form its not working. `ForbiddenError: invalid csrf token` .

**Header on google chome once I sent a form**

>Request URL: http://localhost:5000/
Request Method: POST
Status Code: 403 Forbidden
Remote Address: [::1]:5000
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Length: 1748
Content-Security-Policy: default-src 'none'
Content-Type: text/html; charset=utf-8
Date: Thu, 28 May 2020 15:29:40 GMT
X-Content-Type-Options: nosniff
X-Powered-By: Express
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 1569
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryZSbdQHovB69pA6mB
Cookie: connect.sid=s%3AT4FlgBFpCtcHjnNcT-VCSEUNbg6eyFr1.N0iwA4ImU5fTfBgobHVJz9uinqflVMV3k9UYdgG2m5w; _csrf=M-lh0ofk8UxWJIh_EiQbJE12; XSRF-TOKEN=S8WShoF0-YyTR8ar9CtUqEo4QjLuFBaIGP0c
Host: localhost:5000
Origin: http://localhost:5000
Referer: http://localhost:5000/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
name: 
phone: 
email: 
suburb: 
state: 
propertyType: 
propertyTypeCondition: 
landSize: 
bedrooms: 
bathrooms: 
carspace: 
situation: 
inquiry: (binary)
detail: lorem impisum
_csrf: hMVIB41M-DR1Yq7PZV05y0eMHGquR-SW7tlw

**App.js**
<pre>const express = require("express");
const mongoose = require("mongoose");
var cookieParser = require("cookie-parser");
const csrf = require("csurf");
const cors = require("cors");
const path = require("path");
const bodyParser = require("body-parser");
const session = require("express-session");
const flash = require("connect-flash");
const MongoDbStore = require("connect-mongodb-session")(session);
const app = express();
const PORT = process.env.PORT || 5000;
const adminRoute = require("./routes/admin");
const authRoute = require("./routes/auth");
const evaluationRoute = require("./routes/evaluation");

const store = new MongoDbStore({
  uri: process.env.DB_URL,
  collection: "session",
});
// var csrfProtection = csrf();
var csrfProtection = csrf({ cookie: true });

app.set("view engine", "ejs");
app.set("views", "views");
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(cors());
app.use(flash());
app.use(
  session({
    secret: "My session",
    resave: false,
    saveUninitialized: false,
    store: store,
  })
);
app.use(csrfProtection);
app.use((req, res, next) => {
  var token = req.csrfToken();
  res.cookie("XSRF-TOKEN", token);
  res.locals.csrfToken = token;
  next();
});

app.use("/admin", adminRoute);
app.use("/auth", authRoute);
app.use(evaluationRoute);

app.use("/", express.static("uploads"));
app.use(express.static(path.join(__dirname, "public")));

mongoose
  .connect(process.env.DB_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    useCreateIndex: true,
  })
  .then(() => {
    console.log("Connected to database!");
    app.listen(PORT, (req, res) => {
      console.log("Server running on port", PORT);
    });
  })
  .catch(() => {
    console.log("Connection failed!");
  });
</pre>

Get request token and post request token are match as well. I already check it. Please help me to solve this issue. I wast lot of time with this.

**Comment by saan099** [comment]
Hi, have you guys got any update or alternative on this issue? we've got the same issue, it comes occasionally but blocks all our posts requests on the page and so far we haven't been able to recreate it intentionally. What our observations are is that it's happening when we are navigating different pages after login, so it doesn't seem to be a race condition involving session saving, and we are using mysql in our case to save the secret. Refreshing the page or going to another and coming back makes the issue go away for the same bunch of requests.

**Comment by Monokai** [comment]
@saan099 Unfortunately I still have issues with this. Maybe it has to do with #214, I'm using nginx as a reverse proxy.

**Comment by Monokai** [comment]
I've noticed a pattern. All routes that include middleware that checks if a user is authenticated via Passport (calling `next()` when `req.isAuthenticated() === true`) *never* give invalid csrf token errors. The other routes without this middleware *sometimes* show errors.

@dougwilson does this say anything to you? I've scoured the entire internet looking for a clue to no avail.

**Comment by Monokai** [comment]
Allright, I've solved it for my specific case. I had implemented the extra fetch request to get a csrf token because I thought it wasn't possible to cache the page and still include a generated csrf token. But I've rebuilt the way I'm caching the content so that I can also include a generated token in the meta tag. Basically I'm using some sort of component-level caching and adding the meta tag in a later stage. This seems to work so far.

I've never understood why my previous attempt with the extra fetch request sometimes didn't work, but at least I got rid of the errors now.

**Comment by tomeczekstecc** [comment]
I get this error ("403 - invalid csrf token") everytime (like over 100 times in exact way) after every rebuild (React-nodejs-express-session-csurf). 
The stangest thing is that:
- it apears not just after rebuild - only few houts later - just afret rebuild it works fine (involves Github actions, DigitalOcean Nginx) - if happened so many times that this is checked pattern
- restarting Ngonx doesn't help
- restaring backend doesn't  help
- making another rebuild doesn't help
The only thing that help is to restart whole Droplet on DO and restart backend.

I don't use cookies - nut req.body._csrf solution. I request for csrf token then Id include that to body.

Any ideas?

**Comment by leungkimho** [comment]
New to csurf and node-express, but I've been experiencing the same issue with the `invalid csrf token` sometimes happening.  Like @js-kyle I'm running `csurf` with `express-session` and `connect-mongo`.

When I first ran into the problem of the `invalid csrf token` last week, I ended up flipping the `secure` setting on the cookie option of `express-session` and it started working.  Afterwards I toggled the setting back and forth a few times and wasn't getting the `invalid csrf token`.  This behavior seemed weird to me, so I ran some UI testing today and hopefully this helps narrow down where the issue is.  My suspicion is it may have something to do with `express-session`.

For the tests, I ran Chrome on my app that has a login page with the _csrf token.  I tested the behavior of my login page when I open a new tab, a new window, and a new incognito window.  I ran both my local dev environment running a local MongoDB instance and a remote instance with MongoDB Atlas.

- If `express-session` `cookie.secure` is `false`, I do not get any `invalid csrf token` errors.
- If `express-session` `cookie.secure` is `false`, login/logout then toggle to `true` (and server reset), all previously opened tabs/windows will log in as long as the session hasn't expired.  A new tab, new window, and a new incognito window from a previously logged-in incognito window will log in, but a new incognito window from a non-incognito window will return `invalid csrf token`.
- If `express-session` `cookie.secure` is `true` (and I clear all sessions from the database), all instances return `invalid csrf token`.  This one confuses me as I would expect it from my local server that doesn't have https but not from my remote instance that has https.

From what I'm reading and the behavior I tested, it doesn't seem like it's `csurf` itself.  Unless I'm not fully understanding how sessions work, I would theorize that the "sometimes" behavior others experienced is related to `express-session`.  I would be curious to know if anyone using `cookie-parser` with `csurf({cookie: true})` is experiencing the same issues.

Not versed enough myself to dig in and fix, but hopefully this info may be useful to someone regularly working with the code (@dougwilson ?).  Hopefully it's on the right track to a solution soon.  Thanks!

**Comment by dougwilson** [comment]
Hi @leungkimho thank you for that information. I could speculate on a few different causes, but what would be even better if you are able to provide a reproduction case so it can be reproduced on our end so we can debug and assess what is happening. If you are unable to, we welcome you to attach a debugger to your instance(s) to help track down a PR a fix, of course.

**Comment by leungkimho** [comment]
@dougwilson Anything I can do to help.  Sorry for being a complete newb here, but can you direct me to where I need to go to get you the information you need?

**Comment by dougwilson** [comment]
Hi @leungkimho thanks for the help! Are you asking how you can transfer me your app and instructions or how to debug to figure out the issue on your own instance?

**Comment by leungkimho** [comment]
Transfer

**Comment by dougwilson** [comment]
You can upload the source code to GitHub and drop a link to it. If it's private, then you can always create a private repo on GitHub in your user account and then invite my user to contribute to it. At least, this is how folks have done it in the past.

**Comment by tandrewnichols** [comment]
@leungkimho I am experiencing this using cookies rather than sessions.

**Comment by ghs** [comment]
In my/our case, the setup also involves mongo, csurf and express session. No matter the cookie security property, no matter if changed to session, same result: "invalid csrf token". I suspect is some race condition related to outdated csrf module dependencies.
